"""Update DB

Revision ID: 641b06e6d6ae
Revises: da26574f1e7b
Create Date: 2025-02-13 23:32:39.131385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641b06e6d6ae'
down_revision = 'da26574f1e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_usage')
    # ### end Alembic commands ###
